### ISSUE TITLE
bug...

### ISSUE THREAD

**Issue by q32784307** [HelloYeah/ChooseLocation#2]
有bug ，选择完省市区后，再此点击选择地址，再选择同样的地址，会出现多个请选择。
还有，麻烦我能问一下么？你的数据是用plist文件做的，区的id没有，如果后台要求传id的话，怎么办，如果我自己用xml做数据源的话，要想替换你的plist，还需要改源码...这个数据这里能不能放到外面呢,或者，作者有什么好的解决办法?

**Comment by HelloYeah** [comment]
项目里我是用数据库存的。你说的这个Bug，在项目中也发现了。github没更新
